<?php include("connection.php") ?>
<?php 
 $all = " SELECT * FROM student_info ORDER BY 'StudentName' ASC";

 $alldata = mysqli_query($conn, $all);

//  $totalrow = mysqli_num_rows($alldata);
$html ='<table><tr><td>Reg Date</td><td>Stud Image</td><td>Scholar No</td><td>Student Name</td><td>DateOfBirth</td><td>Contact No</td><td>Aadhar No</td><td>Mail Id</td><td>Father Name</td><td>Father Occupation</td><td>Father ContactNo</td><td>Mother Name</td><td>Mother Occupation</td><td>College Name</td><td>Course Name</td><td>Branch</td><td>Semester</td><td>Session</td><td>Category</td><td>Admission Under</td><td>Minority Community</td><td>Residency</td><td>Living</td><td>Locality</td><td>City</td><td>State</td><td>Pincode</td><td>Local Address</td><td>Guardian Name</td><td>Guardian ContactNo</td><td>10th Schooling</td><td>10th Board</td><td>10th PassingYear</td><td>10th Marks</td><td>10th StudyMedium</td><td>12th Schooling</td><td>12th Board</td><td>12th PassingYear</td><td>12th Marks</td><td>12th StudyMedium</td><td>Diploma College</td><td>Diploma University</td><td>Diploma PassingYr</td><td>Diploma Marks</td><td>DiplomaStudy Medium</td><td>Graduation College</td><td>Graduation University</td><td>Graduation PassingYr</td><td>Graduation Marks</td><td>GraduationStudy Medium</td><td>EntranceExam Name</td><td>EntranceExam year</td><td>Entrance marks</td><td>EntranceExam Medium</td>';
while ($finalresult = mysqli_fetch_assoc($alldata))
{
    $html.='<tr><td>'. $finalresult['RegDate'] .'</td><td>'. $finalresult['StudImage'] .'</td><td>'. $finalresult['ScholarNo'] .'</td><td>'. $finalresult['StudentName'] .'</td><td>'. $finalresult['DateOfBirth'] .'</td><td>'. $finalresult['ContactNo'] .'</td><td>'. $finalresult['AadharNo'] .'</td><td>'. $finalresult['Mailid'] .'</td><td>'. $finalresult['FatherName'] .'</td><td>'. $finalresult['FatherOccupation'] .'</td><td>'. $finalresult['FatherContactNo'] .'</td><td>'. $finalresult['MotherName'] .'</td><td>'. $finalresult['MotherOccupation'] .'</td><td>'. $finalresult['CollegeName'] .'</td><td>'. $finalresult['CourseName'] .'</td><td>'. $finalresult['Branch'] .'</td><td>'. $finalresult['Semester'] .'</td><td>'. $finalresult['AcademicSession'] .'</td><td>'. $finalresult['Category'] .'</td><td>'. $finalresult['AdmissionUnder'] .'</td><td>'. $finalresult['MinorityCommunity'] .'</td><td>'. $finalresult['Residency'] .'</td><td>'. $finalresult['Living'] .'</td><td>'. $finalresult['Locality'] .'</td><td>'. $finalresult['City'] .'</td><td>'. $finalresult['HomeState'] .'</td><td>'. $finalresult['Pincode'] .'</td><td>'. $finalresult['LocalAddress'] .'</td><td>'. $finalresult['GuardianName'] .'</td><td>'. $finalresult['GuardianContactNo'] .'</td><td>'. $finalresult['10thSchooling'] .'</td><td>'. $finalresult['10thBoard'] .'</td><td>'. $finalresult['10thPassingYear'] .'</td><td>'. $finalresult['10thMarks'] .'</td><td>'. $finalresult['10thStudyMedium'] .'</td><td>'. $finalresult['12thSchooling'] .'</td><td>'. $finalresult['12thBoard'] .'</td><td>'. $finalresult['12thPassingYear'] .'</td><td>'. $finalresult['12thMarks'] .'</td><td>'. $finalresult['12thStudyMedium'] .'</td><td>'. $finalresult['DiplomaCollege'] .'</td><td>'. $finalresult['DiplomaUniversity'] .'</td><td>'. $finalresult['DiplomaPassingYr'] .'</td><td>'. $finalresult['DiplomaMarks'] .'</td><td>'. $finalresult['DiplomaStudyMedium'] .'</td><td>'. $finalresult['GraduationCollege'] .'</td><td>'. $finalresult['GraduationUniversity'] .'</td><td>'. $finalresult['GraduationPassingYr'] .'</td><td>'. $finalresult['GraduationMarks'] .'</td><td>'. $finalresult['GraduationStudyMedium'] .'</td><td>'. $finalresult['EntranceExamName'] .'</td><td>'. $finalresult['EntranceExamyear'] .'</td><td>'. $finalresult['EntrancEmarks'] .'</td><td>'. $finalresult['EntranceExamMedium'] .'</td>';
}
$html.='</table>';
header('Content-Type:application/xls');
header('Content-Disposition:attachment;filename=student_details.xls');
echo $html;
?>
